### ISSUE TITLE
404 file not found?

### ISSUE THREAD

**Issue by chadpriddle** [admsev/jquery-play-sound#12]
The fiddle doesn't work anymore?

**Comment by admsev** [comment]
Thanks for reporting! I'd really appreciate hotfix if any

**Comment by chadpriddle** [comment]
looks like you have to put the file extension in now?

**Comment by jord-love** [comment]
jsfiddle not working without the extension for me either. I had to add the .mp3 extension on the URL.

**Comment by admsev** [comment]
Updated README, jsfiddle. Closing the issue
